spring:
  datasource:
    url: jdbc:mariadb://${DB_DESENV_SERVER:localhost}:${DB_DESENV_PORT:3306}/${DB_DESENV_NAME:cp3-seguradora}?createDatabaseIfNotExist=true
    username: ${DB_DESENV_USERNAME:root}
    password: ${DB_DESENV_PASSWORD:root}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create

