spring:
  datasource:
    url: jdbc:oracle:${DB_HOMOLOG_SERVER:thin:@oracle.fiap.com.br}:${DB_HOMOLOG_PORT:1521}:${DB_HOMOLOG_NAME:ORCL}
    username: ${DB_HOMOLOG_USERNAME:RM551377}
    password: ${DB_HOMOLOG_PASSWORD:211204}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
